	rm    src/main/webapp/templates/screens/xnat_imageSessionData/actions.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/edit/edit.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/edit/scans.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/edit/validate.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/upload/xnat_imageSessionData_fields.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/upload/xnat_imageSessionData_instr.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/upload/xnat_imageSessionData_label.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/upload/xnat_imageSessionData_scans.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/upload/xnat_imageSessionData_validation.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/xnat_imageSessionData_assessments.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/xnat_imageSessionData_details.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/xnat_imageSessionData_keyFields.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/xnat_imageSessionData_reconstructions.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/xnat_imageSessionData_report.vm
	rm    src/main/webapp/templates/screens/xnat_imageSessionData/xnat_imageSessionData_scans.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData/edit/scans.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData/edit/validate.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData/upload/xnat_mrSessionData_fields.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData/upload/xnat_mrSessionData_scans.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData/xnat_mrSessionData_details.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData/xnat_mrSessionData_keyFields.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData/xnat_mrSessionData_reconstructions.vm
	rm    src/main/webapp/templates/screens/xnat_mrSessionData_summary.vm
